feign:
    client:
        config:
            default:
                readTimeout: 1000
                connectTimeout: 500

service:
    base:
        url: http://localhost:8083/springDataDemo
    name: feignUserService
